name: Native Build & Test

env:
  cacheId: "11" # increment to expire the cache
  appBuildNumber: ${{ github.run_number }}
  appBuildVersion: "0.7.5"

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - aries-cloudagent-python/**
      - aries-cloudagent-python
  pull_request:
    branches: [main]
    paths:
      - aries-cloud-agent-python/**
jobs:
  watch-demo:
    runs-on: ubuntu-18.04
    name: Demo
    steps:
      - uses: actions/checkout@v2
      
      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          
      # Watch for changes to the HEAD ref, use
      # git for cache keys.
      - name: Generate cache key
        run: |
          echo $(git rev-parse HEAD:aries-cloudagent-python/demo) > ./dd-cache-key.txt
