name: Native Build & Test

env:
  cacheId: "11" # increment to expire the cache
  appBuildNumber: ${{ github.run_number }}
  appBuildVersion: "0.7.5"

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - aries-cloudagent-python/**
      - aries-cloudagent-python
  pull_request:
    branches: [main]
    paths:
      - aries-cloud-agent-python/**

